### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by jomei** [art2rik/KupibiletTestAPI#1]
Привет!
Замечания по твоему решению:

1. .idea в гите
2. Отсутствие Gemfile. Чтобы запуститься надо устанавливать все гемы по очереди через gem install
3. Синхронный редис в асинхронном приложении. Сейчас каждое обращение к редису полностью блокирует event loop
4. spec?
5. config? как кастомизировать подключение к редису?

Можно оформить фиксы в pull request и пингануть в нем меня, или любым удобным способом.

**Comment by art2rik** [comment]
Доброе утро! Фиксы сделал, все в том же репозитории (
https://github.com/art2rik/KupibiletTestAPI)

2 июля 2018 г., 15:30 пользователь Anatoly Nosov <notifications@github.com>
написал:

**Comment by art2rik** [comment]
@jomei Пофиксил
